# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/comm.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'proto/comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/comm.proto\x12\x08protocol\"\xd3\x01\n\x07Message\x12\x12\n\nclientguid\x18\x01 \x01(\x0c\x12*\n\nchunkstart\x18\x02 \x01(\x0b\x32\x14.protocol.ChunkStartH\x00\x12(\n\tchunkdata\x18\x03 \x01(\x0b\x32\x13.protocol.ChunkDataH\x00\x12(\n\tpollquery\x18\x04 \x01(\x0b\x32\x13.protocol.PollQueryH\x00\x12*\n\ninfopacket\x18\x05 \x01(\x0b\x32\x14.protocol.InfoPacketH\x00\x42\x08\n\x06packet\"0\n\nChunkStart\x12\x0f\n\x07\x63hunkid\x18\x01 \x01(\x05\x12\x11\n\tchunksize\x18\x02 \x01(\x05\">\n\tChunkData\x12\x0f\n\x07\x63hunkid\x18\x01 \x01(\x05\x12\x10\n\x08\x63hunknum\x18\x02 \x01(\x05\x12\x0e\n\x06packet\x18\x03 \x01(\x0c\"\x0b\n\tPollQuery\"\x1e\n\nInfoPacket\x12\x10\n\x08hostname\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=31
  _globals['_MESSAGE']._serialized_end=242
  _globals['_CHUNKSTART']._serialized_start=244
  _globals['_CHUNKSTART']._serialized_end=292
  _globals['_CHUNKDATA']._serialized_start=294
  _globals['_CHUNKDATA']._serialized_end=356
  _globals['_POLLQUERY']._serialized_start=358
  _globals['_POLLQUERY']._serialized_end=369
  _globals['_INFOPACKET']._serialized_start=371
  _globals['_INFOPACKET']._serialized_end=401
# @@protoc_insertion_point(module_scope)
